### PR TITLE
Add classpath search if no configuration file is found (Fix #124)

### LINKED ISSUE #124: Classpath property
I did an update in the past to be able to load the config.properties from the classpath.
It has been removed with recent modification.

Why loading from the classpath, this way you distribute to your team a simple jar that is already configured for your environment, and the packaging is simple:
```
zip okta.jar config.properties
```

Should I start using a fork or will you consider adding it back?

As a side note, I'm at Oktane

### PR DESCRIPTION
**Pull request by loopingz**
Problem Statement
-----------------
https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/124
The classpath used to be resolved if a configuration file was not present

Solution
--------
Add back this resolution

### CODE REVIEW

**Comment by AlainODea** [comment]
@loopingz thanks! I'll give this a run through my manual tests now.

**Comment by AlainODea** [comment]
@loopingz Matt is on vacation for a couple of weeks so it might be a while before this gets merged.

I won't be at DEF CON or Black Hat this year, unfortunately. Perhaps I'll get to Oktane19 though. Are you planning to attend that?

**Comment by AlainODea** [comment]
@bdemers @andreihava-okta do you know who has merge rights while Matt is out on vacation? If it's no one, I'll pause things and let contributors know.

**Comment by rdegges** [comment]
Matt is indeed out, but I'll merge this in. I also just made you an official collaborator, @AlainODea <3

Your contributions have been awesome and are much appreciated! Welcome to the team! =D

**Comment by AlainODea** [comment]
Woot 🎉  Thank you, @rdegges 😄

**Comment by rdegges** [comment]
Nooo, thank YOU! It takes a community to build awesome stuff.

**Pull request merged**
