### PR TITLE
:memo: Update readme

### PR DESCRIPTION
**Pull request by nbarbettini**
Problem Statement
-----------------

Readme was confusing.

Solution
--------

Restructure to be less confusing, especially:

* Avoid talking too much about specific platforms (thanks @AlainODea)
* Keep the getting started instructions simple and clear at the top

### CODE REVIEW

**Comment by nbarbettini** [comment]
I merged @AlainODea's PR #90 and made some changes of my own. No real changes to content, just reformatting and restructuring the readme.

I think it's much clearer now, but cc @AlainODea @andreihava-okta @mraible just in case you think something doesn't look right. 😄

**Comment by AlainODea** [comment]
@nbarbettini this is great 👍

@mraible this is good to merge.

**Comment by mraible** [comment]
@AlainODea - @nbarbettini is on my team, so he can merge too! 🙂

**Comment by AlainODea** [comment]
Nice! 😊

**Pull request merged**
