### PR TITLE
:art: Use Maven-based dependencies

### PR DESCRIPTION
**Pull request by AlainODea**
- Allow out of the box build with mvn CLI tool

 - Move dependencies from source repo to POM XML

 - Use Maven Shade Plugin to build batteries-included JAR

### CODE REVIEW

**Comment by cosmin** [comment]
same as #42, either one of these should be merged to move the build to Maven.

**Comment by rdegges** [comment]
Hi there, is this ready for merging?

Sorry for the delay: we haven't had a maintainer for this library in a while. I'm going through and merging changes that are production ready. If this works, please let me know and I'll merge =)

**Comment by AlainODea** [comment]
I haven’t tested this in a while. I’ll give it a spin and make sure it still works.

**Comment by rdegges** [comment]
Ya! Let me know! If you can resolve the merge conflicts, etc. I'll merge it in =D

**Comment by AlainODea** [comment]
@rdegges I have master merged in, and I have this retested and ready to merge.

I really like the cleaned up POM on master 💯

I just took it carte blanche. It is vastly better than my first attempt. Nice work @DarioAmiri 👍

**Comment by rdegges** [comment]
Awesome! Thank you =D

**Comment by AlainODea** [comment]
@rdegges my pleasure. Thank you for maintaining this useful project!

**Pull request merged**
