### PR TITLE
:seedling: Support for credential_process

### LINKED ISSUE #59: Support for credential_process
This was talked about in the recent [AWS CLI talk at re:Invent ](http://awsfeed.com/post/168047446129/aws-reinvent-2017-aws-cli-2017-and-beyond)

By supporting returning a specific JSON object, as described here:  http://docs.aws.amazon.com/cli/latest/topic/config-vars.html#sourcing-credentials-from-external-processes [okta-aws-cli-assume-role](https://github.com/oktadeveloper/okta-aws-cli-assume-role) can integrate better with the [aws-cli](https://aws.amazon.com/cli/) command. 

See example here:  https://github.com/awslabs/awsprocesscreds 

/cc: @AlainODea @mraible @rdegges @joelfranusic-okta

### PR DESCRIPTION
**Pull request by AlainODea**
Problem Statement
-----------------
Issue #59 states:
> This was talked about in the recent [AWS CLI talk at re:Invent ](http://awsfeed.com/post/168047446129/aws-reinvent-2017-aws-cli-2017-and-beyond)
> 
> By supporting returning a specific JSON object, as described here: http://docs.aws.amazon.com/cli/latest/topic/config-vars.html#sourcing-credentials-from-external-processes [okta-aws-cli-assume-role](https://github.com/oktadeveloper/okta-aws-cli-assume-role) can integrate better with the [aws-cli](https://aws.amazon.com/cli/) command.
> 
> See example here: https://github.com/awslabs/awsprocesscreds
> 
> /cc: @AlainODea @mraible @rdegges @joelfranusic-okta

Solution
--------
 - Add CredentialProcess entry-point

 - Move logging/console interaction to STDERR (allow 2>/dev/null)

 - Depends on #201 unless you only have one AWS role assigned in Okta

Resolves #59

### CODE REVIEW

**Comment by AlainODea** [comment]
@mmahadevan-okta are you up for code-reviewing this?

**Comment by mmahadevan-okta** [comment]
I would not be the right person to code review it.  :( But perhaps @tom-smith-Okta can help? Tom?

**Comment by AlainODea** [comment]
CredentialProcess would be run from the command-line. I suppose it’s probably a good idea to create awscreds-okta or something similar to make this easier to consume.

**Comment by tom-smith-okta** [comment]
@AlainODea I'm sure your code is greta. The nice thing about the credential_process keyword is that it allows you to keep the "regular" aws commands and profile system in place. So I can set up my `~/.aws/config` file with an entry like:
```
[profile okta01]
credential_process = okta-aws-cli-1.0.3.jar -param1 xyz -param2 123
```
and then I can invoke this profile by using
`aws s3 ls --profile okta01`
I just wasn't sure if your setup would allow this kind of invocation.

**Comment by AlainODea** [comment]
@tom-smith-okta you are right. The more people use this, the more I realize overriding the **aws** command was a bad idea. I’m going to remove that from the installer in an upcoming PR.

**Comment by AlainODea** [comment]
`java -jar okta-aws-cli.jar com.okta.tools.CredentialProcess` would run this entry point. I’m also realizing that I should support command-line options for all the env and config file options to make this kind of use really practical.

**Comment by AlainODea** [comment]
@tom-smith-okta are you okay with me merging this and following up with the installer fix. Is there anything essential I should do before merging it?

**Comment by tom-smith-okta** [comment]
Absolutely OK with that


________________________________

**Pull request merged**
