### PR TITLE
Sts duration

### PR DESCRIPTION
**Pull request by slancio**
Problem Statement
-----------------
Currently the STS session duration is hard coded to 1 hour.  Amazon has recently increased the maximum duration to 12 hours which can be set on the role.

Solution
--------
Add an environment variable to specify the STS session duration in seconds.

### CODE REVIEW

**Comment by AlainODea** [comment]
Nice work! I’ll test this today. Thank you, @slancio.

**Comment by AlainODea** [comment]
@slancio this is solid. It passes the test suite and all my manual tests. It's a cleanly written feature addition. Thank you!

You also documented it which I forgot to due with OKTA_BROWSER_AUTH, so I'll have to get on that.

@mraible this is ready to be merged.

**Comment by AlainODea** [comment]
Fixes #38 and #108.

**Comment by uvreut** [comment]
@AlainODea @mraible 
Is it possible to issue a new release with this change?

**Comment by mraible** [comment]
Yep!

**Comment by uvreut** [comment]
It's missing the .jar file

**Comment by mraible** [comment]
@uvreut Fixed!

**Pull request merged**
