### PR TITLE
Allows to choose the target account

### PR DESCRIPTION
**Pull request by liquid-sky**
If cross-account role is linked to multiple accounts.

Will assume the existing role by default if the cross-account role is linked to only one account.

```
Please choose the role you would like to assume:
[ 1 ]: arn:aws:iam::<REDACTED_IDENTITY_ACCOUNT>:role/<REDACTED_CROSS_ACCOUNT_ROLE1>
[ 2 ]: arn:aws:iam::<REDACTED_IDENTITY_ACCOUNT>:role/<REDACTED_CROSS_ACCOUNT_ROLE2>
[ 3 ]: arn:aws:iam::<REDACTED_IDENTITY_ACCOUNT>:role/<REDACTED_CROSS_ACCOUNT_ROLE3>
[ 4 ]: arn:aws:iam::<REDACTED_IDENTITY_ACCOUNT>:role/<REDACTED_CROSS_ACCOUNT_ROLE4>
Selection: 4
15:14:34 [main] DEBUG com.okta.tools.awscli - Creating the AWS Identity Management client
15:14:34 [main] DEBUG com.okta.tools.awscli - Getting role: <REDACTED_CROSS_ACCOUNT_ROLE4>
15:14:35 [main] DEBUG com.okta.tools.awscli - GetRoleResult: {Role: {Path: /,RoleName: <REDACTED_CROSS_ACCOUNT_ROLE4>,RoleId: <REDACTED_ROLE_ID>,Arn: arn:aws:iam::<REDACTED_IDENTITY_ACCOUNT>:role/<REDACTED_CROSS_ACCOUNT_ROLE4>,CreateDate: Mon Nov 28 09:56:35 GMT 2016,AssumeRolePolicyDocument: <REDACTED_POLICY_DOCUMENT>
15:14:35 [main] DEBUG com.okta.tools.awscli - getRole: {Path: /,RoleName: <REDACTED_CROSS_ACCOUNT_ROLE4>,RoleId: <REDACTED_ROLE_ID>,Arn: arn:aws:iam::<REDACTED_IDENTITY_ACCOUNT>:role/<REDACTED_CROSS_ACCOUNT_ROLE4>,CreateDate: Mon Nov 28 09:56:35 GMT 2016,AssumeRolePolicyDocument: <REDACTED_POLICY_DOCUMENT>
15:14:35 [main] DEBUG com.okta.tools.awscli - ListAttachedRolePoliciesResult: {AttachedPolicies: [{PolicyName: <REDACTED_POLICY>,PolicyArn: arn:aws:iam::<REDACTED_IDENTITY_ACCOUNT>:policy/<REDACTED_POLICY>}],IsTruncated: false,}
15:14:35 [main] DEBUG com.okta.tools.awscli - ListRolePoliciesResult: {PolicyNames: [],IsTruncated: false,}
15:14:35 [main] DEBUG com.okta.tools.awscli - There are no inlines policies
15:14:35 [main] DEBUG com.okta.tools.awscli - Selected policy {PolicyName: <REDACTED_POLICY>,PolicyArn: arn:aws:iam::<REDACTED_IDENTITY_ACCOUNT>:policy/<REDACTED_POLICY>}
15:14:35 [main] DEBUG com.okta.tools.awscli - GetPolicyResult: {PolicyName: <REDACTED_POLICY>,PolicyArn: arn:aws:iam::<REDACTED_IDENTITY_ACCOUNT>:policy/<REDACTED_POLICY>}
15:14:35 [main] DEBUG com.okta.tools.awscli - GetPolicyVersionResult: {PolicyVersion: {Document: <REDACTED_POLICY_DOCUMENT>,VersionId: v1,IsDefaultVersion: true,CreateDate: Mon Nov 28 09:55:54 GMT 2016}}
15:14:35 [main] DEBUG com.okta.tools.awscli - Clean Policy Document: {
    "Version": "2012-10-17",
    "Statement": {
        "Effect": "Allow",
        "Action": "sts:AssumeRole",
        "Resource": [
            "arn:aws:iam::<REDACTED_LINKED_ACCOUNT_3>:role/<REDACTED_LINKED_ACCOUNT_ROLE>",
            "arn:aws:iam::<REDACTED_LINKED_ACCOUNT_2>:role/<REDACTED_LINKED_ACCOUNT_ROLE>",
            "arn:aws:iam::<REDACTED_LINKED_ACCOUNT_1>:role/<REDACTED_LINKED_ACCOUNT_ROLE>"
        ]
    }
}
15:14:35 [main] DEBUG com.okta.tools.awscli - Statement node: {"Effect":"Allow","Action":"sts:AssumeRole","Resource":["arn:aws:iam::<REDACTED_LINKED_ACCOUNT_3>:role/<REDACTED_LINKED_ACCOUNT_ROLE>","arn:aws:iam::<REDACTED_LINKED_ACCOUNT_2>:role/<REDACTED_LINKED_ACCOUNT_ROLE>","arn:aws:iam::<REDACTED_IDENTITY_ACCOUNT>:role/<REDACTED_LINKED_ACCOUNT_ROLE>"]}
15:14:35 [main] DEBUG com.okta.tools.awscli - Statement is NOT array
15:14:35 [main] DEBUG com.okta.tools.awscli - Resource node: ["arn:aws:iam::<REDACTED_LINKED_ACCOUNT_3>:role/<REDACTED_LINKED_ACCOUNT_ROLE>","arn:aws:iam::<REDACTED_LINKED_ACCOUNT_2>:role/<REDACTED_LINKED_ACCOUNT_ROLE>","arn:aws:iam::<REDACTED_IDENTITY_ACCOUNT>:role/<REDACTED_LINKED_ACCOUNT_ROLE>"]
15:14:35 [main] DEBUG com.okta.tools.awscli - Role resource: arn:aws:iam::<REDACTED_LINKED_ACCOUNT_3>:role/<REDACTED_LINKED_ACCOUNT_ROLE>
15:14:35 [main] DEBUG com.okta.tools.awscli - Role resource: arn:aws:iam::<REDACTED_LINKED_ACCOUNT_2>:role/<REDACTED_LINKED_ACCOUNT_ROLE>
15:14:35 [main] DEBUG com.okta.tools.awscli - Role resource: arn:aws:iam::<REDACTED_IDENTITY_ACCOUNT>:role/<REDACTED_LINKED_ACCOUNT_ROLE>
Select target account role:
[ 1 ]: arn:aws:iam::<REDACTED_LINKED_ACCOUNT_3>:role/<REDACTED_LINKED_ACCOUNT_ROLE>
[ 2 ]: arn:aws:iam::<REDACTED_LINKED_ACCOUNT_2>:role/<REDACTED_LINKED_ACCOUNT_ROLE>
[ 3 ]: arn:aws:iam::<REDACTED_IDENTITY_ACCOUNT>:role/<REDACTED_LINKED_ACCOUNT_ROLE>
Selection: 1
15:14:47 [main] DEBUG com.okta.tools.awscli - [profile <REDACTED_IDENTITY_ACCOUNT>/<REDACTED_CROSS_ACCOUNT_ROLE4>/<REDACTED_USERNAME>]
15:14:47 [main] DEBUG com.okta.tools.awscli - role_arn=arn:aws:iam::<REDACTED_LINKED_ACCOUNT_3>:role/<REDACTED_LINKED_ACCOUNT_ROLE>
15:14:47 [main] DEBUG com.okta.tools.awscli - source_profile=<REDACTED_IDENTITY_ACCOUNT>/<REDACTED_CROSS_ACCOUNT_ROLE4>/<REDACTED_USERNAME>
15:14:47 [main] DEBUG com.okta.tools.awscli - region=us-east-1
....
```

### CODE REVIEW

**Comment by liquid-sky** [comment]
Resolves [this issue](https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/17)

**Comment by raphaellondner-okta** [comment]
Can you try the latest version of this tool? This should have been fixed, provided you're using managed policies only, and each policy only has one single AssumeRole permission (to a cross-account role).

**Comment by liquid-sky** [comment]
Yup we rely on managed policies, but instead of having a policy per linked account (which can lead to a large number of policies), we use a policy per role, where each policy contains an array of linked account role ARNs (see snipped above). I've tried the latest version and it still fails to process multiple ARNs in a single policies as it expects it to be a String value.

**Comment by raphaellondner-okta** [comment]
@liquid-sky That makes sense, thanks for the clarification. I've modified the tool role arrays in the AssumeRole action, can you test it and see if that works for you?

**Comment by liquid-sky** [comment]
@raphaellondner-okta sure, is there a branch that I can test?

**Comment by raphaellondner-okta** [comment]
@liquid-sky It is actually in the master branch already (yes, I know it's not a best practice, but the change was fairly easy and doesn't affect the officially supported use case).

**Comment by liquid-sky** [comment]
Are you sure the changes have been pushed? I'm unable to find what has changed. The last time I tested was 2nd of December and the last commit in master is from 29th of November: 

```
commit e8504aea284c4bd694c425f7560da024d8f9784d
Merge: 4aae908 8d79d29
Author: Raphael Londner <raphaellondner-okta@users.noreply.github.com>
Date:   Tue Nov 29 01:22:00 2016 -0800

    Merge pull request #15 from oktadeveloper/rl-multi-policy-roles

    Added multi-policy support for cross-account roles
```

**Comment by raphaellondner-okta** [comment]
@liquid-sky Looks like there was a glitch indeed. Can you try again from [this branch](https://github.com/oktadeveloper/okta-aws-cli-assume-role/tree/rl-multi-policy-roles)?

**Comment by liquid-sky** [comment]
@raphaellondner-okta tested it and it works like a charm 👍

**Comment by raphaellondner-okta** [comment]
@liquid-sky Thanks for the positive feedback! :)

**Pull request closed without merging**
