### PR TITLE
Only add/update profile for role to assume

### PR DESCRIPTION
**Pull request by boyvanduuren**
This is a fix for #44. The changes in this PR will make sure that nothing is changed in the credentials and config files except for the profile that corresponds to the role that is assumed.

I've also added test-cases for the new classes I introduced and made some changes to the `pom.xml` so that tests can easily be ran with `mvn test`.

There was also a `NullPointerException` i came across in the existing code (https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/src/main/java/com/okta/tools/awscli.java#L427) which was fixed.

### CODE REVIEW

**Comment by rdegges** [comment]
Dude, this is awesome. Thank you! <3 You are the Okta CLI hero we have all been waiting for!

**Comment by mmahadevan-okta** [comment]
Thank you @boyvanduuren. Absolutely awesome!

**Comment by boyvanduuren** [comment]
You guys are welcome, thanks for merging!

**Comment by sbotman** [comment]
Nice update @boyvanduuren! Tnx

**Pull request merged**
