### PR TITLE
:bug: Closing browser auth doesn't quit

### LINKED ISSUE #163: Closing browser auth window doesn't quit
Manually closing the browser auth window with the embedded browser doesn't quit the program. It stays running in a stuck/broken state.

### PR DESCRIPTION
**Pull request by AlainODea**
Problem Statement
-----------------
> Manually closing the browser auth window with the embedded browser doesn't quit the program. It stays running in a stuck/broken state.

Solution
--------
 - Clicking close exits the application with code 1

Resolves #163

### CODE REVIEW

**Comment by AlainODea** [comment]
@loopingz can you give this a code review for me? 😊

**Comment by loopingz** [comment]
Sure thing

**Comment by loopingz** [comment]
I did a PR on your branch with the result of my test: https://github.com/AlainODea/okta-aws-cli-assume-role/pull/2

**Comment by loopingz** [comment]
👍

**Pull request closed without merging**
