### PR TITLE
Update and cleanup dependencies

### PR DESCRIPTION
**Pull request by jones2026**
Problem Statement
-----------------
Currently there are many unused dependencies in this project

Solution
--------
Remove them

### CODE REVIEW

**Comment by AlainODea** [comment]
@jones2026 thank you for putting this together. Code review wise I have no concerns. It looks good. I'll build and test this branch before I approve just to make sure there aren't surprises. The test coverage is really weak on this unfortunately.

**Comment by AlainODea** [comment]
@jones2026 it looks to be functionally correct but adds a lot of extraneous logging:
```
ep 13, 2018 9:36:05 AM com.amazonaws.auth.profile.internal.BasicProfileConfigLoader loadProfiles
WARNING: Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
Sep 13, 2018 9:36:05 AM com.amazonaws.auth.profile.internal.BasicProfileConfigLoader loadProfiles
WARNING: Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
Sep 13, 2018 9:36:05 AM com.amazonaws.auth.profile.internal.BasicProfileConfigLoader loadProfiles
WARNING: Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
Sep 13, 2018 9:36:05 AM com.amazonaws.auth.profile.internal.BasicProfileConfigLoader loadProfiles
WARNING: Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
Sep 13, 2018 9:36:05 AM com.amazonaws.auth.profile.internal.BasicProfileConfigLoader loadProfiles
WARNING: Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
```

Any idea why that logging is happening? I've tried a few combinations of log4j.properties log4j2.xml and slf4j-nop to no avail.

**Comment by jones2026** [comment]
@AlainODea found the culprit here: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/profile/internal/BasicProfileConfigLoader.java#L95-L100

Looks like the `aws-sdk-java` since version 1.11.377 has starting logging this warning. Haven't taken anytime yet to see how to avoid it

**Comment by AlainODea** [comment]
@jones2026 if it helps the AWS Java SDK was doing a LOG.warn before with a different message so it's not likely the SDK itself but something else impacting the log configuration:
https://github.com/aws/aws-sdk-java/blame/46c00efdd9240d2d20d734f806dcc71506af6e0f/aws-java-sdk-core/src/main/java/com/amazonaws/auth/profile/internal/BasicProfileConfigLoader.java#L96-L99

I tried to do a diff of the v1.0.3 JAR and the v1.0.4-SNAPSHOT based on your change and I got lost trying to find what changed in a meaningful way to impact the logging.

**Comment by AlainODea** [comment]
@jones2026 I think this might bw fine now with the removal of writes to ~/.aws/config. I’ll try again and merge if so.

**Pull request merged**
